# Generated by Django 2.2.5 on 2019-10-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_advocate_survivor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Advocate')),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Survivor')),
            ],
        ),
    ]
